import { compositeShader, normalShader, shadowShader } from './shaders';
import { FilesetResolver, FaceLandmarker, HandLandmarker, type FaceLandmarkerResult, type HandLandmarkerResult } from '@mediapipe/tasks-vision';
import { initTypeGPU } from './typegpu-bridge';
import { estimateVideoDepth, getDepthAt, getSceneLuma, loadDepthModel, isDepthReady } from './depth-estimator';
import { setupLightInput } from './light-input';

const W=960,H=540,WG=8;
const canvas=document.querySelector<HTMLCanvasElement>('#output')!;
const video=document.querySelector<HTMLVideoElement>('#video')!;
const start=document.querySelector<HTMLButtonElement>('#start')!;
const status=document.querySelector<HTMLElement>('#status')!;
const cpuMs=document.querySelector<HTMLElement>('#cpu-ms')!;
const fpsEl=document.querySelector<HTMLElement>('#fps')!;
const inputSize=document.querySelector<HTMLElement>('#input-size')!;
const handIndicator=document.querySelector<HTMLElement>('#hand-indicator')!;
const bulb=document.querySelector<HTMLElement>('#bulb')!;
const lightField=document.querySelector<HTMLElement>('#light-field')!;
const intensityControl=document.querySelector<HTMLInputElement>('#intensity');
let userIntensity=Number(intensityControl?.value??3);
intensityControl?.addEventListener('input',()=>{userIntensity=Number(intensityControl.value);const v=document.querySelector('#intensity-value');if(v)v.textContent=userIntensity.toFixed(1)});

type Palm={x:number,y:number};
type Gpu={device:GPUDevice;context:GPUCanvasContext;format:GPUTextureFormat;depth:GPUTexture;normal:GPUTexture;shadow:GPUTexture;sampler:GPUSampler;normals:GPUComputePipeline;shadows:GPUComputePipeline;composite:GPURenderPipeline;uniformBuffer:GPUBuffer};
let gpu:Gpu;let hand:HandLandmarker|null=null,face:FaceLandmarker|null=null;
let lightX=.5,lightY=.44,lightZ=.42,lightIntensity=0,targetIntensity=0;
let lightActive=true,lastDepthAt=0,depthInFlight=false,lastFrame=performance.now(),frameCount=0,cameraRunning=false,visionLoading=false,palms:Palm[]=[];
const inputAbort=new AbortController();
const lightInput=setupLightInput(canvas,(u)=>{if(u.lightPosition){lightX=u.lightPosition[0];lightY=u.lightPosition[1]}if(u.lightZ!==undefined)lightZ=u.lightZ;lightActive=true;},inputAbort.signal);
function setStatus(message:string){status.textContent=message}
function updateBulb(hiddenByHand=false){const w=canvas.clientWidth||W,h=canvas.clientHeight||H;const x=lightX*w,y=lightY*h;const size=Math.max(42,Math.min(112,66/(.35+lightZ)));bulb.style.left=`${x}px`;bulb.style.top=`${y}px`;bulb.style.width=`${size}px`;bulb.style.height=`${size}px`;bulb.style.opacity=hiddenByHand?'0':'1';bulb.style.transform=`translate(-50%,-50%) scale(${1+.08*Math.sin(performance.now()*.004)})`;const glow=Math.max(.16,Math.min(.52,.16+userIntensity*.055));lightField.style.opacity=hiddenByHand?'0':String(glow);lightField.style.background=`radial-gradient(circle at ${lightX*100}% ${lightY*100}%,rgba(255,226,155,.30) 0%,rgba(255,190,90,.12) 15%,rgba(255,130,40,.035) 35%,transparent 60%)`}
function visionSetup(){return FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.17/wasm').then(v=>Promise.all([HandLandmarker.createFromOptions(v,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:2}),FaceLandmarker.createFromOptions(v,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numFaces:1,outputFacialTransformationMatrixes:true})])).then(([h,f])=>{hand=h;face=f})}
function track(now:number){palms=[];let nearestHand=1;if(hand){const r:HandLandmarkerResult=hand.detectForVideo(video,now);for(const lm of r.landmarks.slice(0,2)){let x=0,y=0;for(const j of [0,5,9,13,17]){x+=lm[j].x;y+=lm[j].y}const p={x:x/5,y:y/5};palms.push(p);nearestHand=Math.min(nearestHand,getDepthAt(p.x,p.y))}}
  const p=palms[0]??palms[1];
  if(p){lightX=p.x;lightY=p.y;lightZ=Math.max(.12,Math.min(.86,getDepthAt(p.x,p.y)-.08));handIndicator.style.display='block';handIndicator.style.left=`${lightX*canvas.clientWidth}px`;handIndicator.style.top=`${lightY*canvas.clientHeight}px`;}else{handIndicator.style.display='none';lightInput.orbitTick();}
  let faceDepth=.5,faceNear=0;
  if(face){const fr:FaceLandmarkerResult=face.detectForVideo(video,now);const pts=fr.faceLandmarks[0];if(pts?.length){const c=pts[1]??pts[0];faceDepth=getDepthAt(c.x,c.y);faceNear=Math.max(0,1-Math.hypot(lightX-c.x,lightY-c.y)*5);}}
  const handOccludes=palms.length>0&&nearestHand<lightZ-.025;
  targetIntensity=lightActive?userIntensity*(1+faceNear*.85+Math.max(0,.5-faceDepth)*.25):0;
  lightIntensity+=(targetIntensity-lightIntensity)*.16;
  updateBulb(handOccludes);
}
function tex(format:GPUTextureFormat,usage:GPUTextureUsageFlags){return gpu.device.createTexture({size:[W,H],format,usage,label:`orbit-${format}`})}
async function init(){if(!navigator.gpu)throw Error('WebGPU is not available. Use Chrome or Edge with WebGPU enabled.');const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error('No GPU adapter.');const device=await adapter.requestDevice();device.addEventListener('uncapturederror',e=>{console.error(e.error);setStatus(`GPU error: ${e.error.message}`)});device.lost.then(info=>setStatus(`GPU lost: ${info.message||info.reason}`));initTypeGPU(device);const context=canvas.getContext('webgpu')!;const format=navigator.gpu.getPreferredCanvasFormat();context.configure({device,format,alphaMode:'premultiplied'});gpu={device,context,format,depth:null as never,normal:null as never,shadow:null as never,sampler:null as never,normals:null as never,shadows:null as never,composite:null as never,uniformBuffer:null as never};gpu.depth=tex('r32float',GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST);gpu.normal=tex('rgba16float',GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING);gpu.shadow=tex('r32float',GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING);gpu.sampler=device.createSampler({magFilter:'linear',minFilter:'linear'});gpu.uniformBuffer=device.createBuffer({size:32,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});const n=device.createShaderModule({code:normalShader}),s=device.createShaderModule({code:shadowShader}),c=device.createShaderModule({code:compositeShader});gpu.normals=device.createComputePipeline({layout:'auto',compute:{module:n,entryPoint:'reconstructNormals'}});gpu.shadows=device.createComputePipeline({layout:'auto',compute:{module:s,entryPoint:'projectShadow'}});gpu.composite=device.createRenderPipeline({layout:'auto',vertex:{module:c,entryPoint:'fullscreen'},fragment:{module:c,entryPoint:'composite',targets:[{format}]},primitive:{topology:'triangle-list'}})}
function uploadDepth(depth:Float32Array){const buffer=new ArrayBuffer(depth.byteLength);new Float32Array(buffer).set(depth);gpu.device.queue.writeTexture({texture:gpu.depth},new Float32Array(buffer),{bytesPerRow:W*4,rowsPerImage:H},{width:W,height:H,depthOrArrayLayers:1})}
function writeFrameUniform(now:number){const data=new ArrayBuffer(32),view=new DataView(data);view.setUint32(0,W,true);view.setUint32(4,H,true);view.setFloat32(8,now/1000,true);view.setFloat32(12,getSceneLuma(),true);view.setFloat32(16,lightX,true);view.setFloat32(20,lightY,true);view.setFloat32(24,lightZ,true);view.setFloat32(28,lightIntensity,true);gpu.device.queue.writeBuffer(gpu.uniformBuffer,0,data)}
function render(now:number){if(!cameraRunning||video.readyState<HTMLMediaElement.HAVE_CURRENT_DATA){requestAnimationFrame(render);return}try{track(now);if(isDepthReady()&&!depthInFlight&&now-lastDepthAt>110){depthInFlight=true;lastDepthAt=now;estimateVideoDepth(video,W,H).then(d=>{if(d)uploadDepth(d)}).catch(e=>setStatus(`Depth runtime error: ${(e as Error).message}`)).finally(()=>depthInFlight=false)}writeFrameUniform(now);const dev=gpu.device,enc=dev.createCommandEncoder({label:'depth-space-point-light'}),ub:GPUBufferBinding={buffer:gpu.uniformBuffer};const np=enc.beginComputePass();np.setPipeline(gpu.normals);np.setBindGroup(0,dev.createBindGroup({layout:gpu.normals.getBindGroupLayout(0),entries:[{binding:0,resource:gpu.depth.createView()},{binding:1,resource:gpu.normal.createView()},{binding:2,resource:ub}]}));np.dispatchWorkgroups(Math.ceil(W/WG),Math.ceil(H/WG));np.end();const sp=enc.beginComputePass();sp.setPipeline(gpu.shadows);sp.setBindGroup(0,dev.createBindGroup({layout:gpu.shadows.getBindGroupLayout(0),entries:[{binding:0,resource:gpu.depth.createView()},{binding:1,resource:gpu.shadow.createView()},{binding:2,resource:ub}]}));sp.dispatchWorkgroups(Math.ceil(W/WG),Math.ceil(H/WG));sp.end();const pass=enc.beginRenderPass({colorAttachments:[{view:gpu.context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,0]}]});pass.setPipeline(gpu.composite);pass.setBindGroup(0,dev.createBindGroup({layout:gpu.composite.getBindGroupLayout(0),entries:[{binding:0,resource:dev.importExternalTexture({source:video})},{binding:1,resource:gpu.sampler},{binding:2,resource:gpu.depth.createView()},{binding:3,resource:gpu.normal.createView()},{binding:4,resource:gpu.shadow.createView()},{binding:5,resource:ub}]}));pass.draw(3);pass.end();dev.queue.submit([enc.finish()]);cpuMs.textContent=`${(performance.now()-now).toFixed(1)} ms`;frameCount++;if(now-lastFrame>500){fpsEl.textContent=`${Math.round(frameCount*1000/(now-lastFrame))} fps`;frameCount=0;lastFrame=now}}catch(e){console.error(e);setStatus(`GPU render error: ${(e as Error).message}`)}requestAnimationFrame(render)}
function visualLoop(){if(cameraRunning)updateBulb(false);requestAnimationFrame(visualLoop)}requestAnimationFrame(visualLoop);
start.addEventListener('click',async()=>{if(cameraRunning)return;try{start.disabled=true;setStatus('Requesting camera permission…');const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},facingMode:'user'},audio:false});video.srcObject=stream;await video.play();cameraRunning=true;inputSize.textContent=`${video.videoWidth}×${video.videoHeight}`;setStatus('Camera running · orbital 3D bulb active · hover, click, drag, wheel or pinch');requestAnimationFrame(render);if(!visionLoading){visionLoading=true;visionSetup().catch(e=>setStatus(`Vision unavailable: ${(e as Error).message}`))}if(!isDepthReady()){loadDepthModel(m=>setStatus(m)).then(()=>setStatus('Depth Anything V2 ready · 3D point light active')).catch(e=>setStatus(`Depth unavailable: ${(e as Error).message}`))}}catch(e){start.disabled=false;setStatus(`Camera failed: ${(e as Error).message}`)}});
(async()=>{try{setStatus('Initializing WebGPU + TypeGPU…');await init();start.disabled=false;setStatus('Ready — start camera.')}catch(e){start.disabled=true;setStatus((e as Error).message)}})();
